"use client";

import Link from "next/link";
import { useState } from "react";
import { ArrowLeft, HeartPulse } from "lucide-react";

export default function SignUp() {
  const [done, setDone] = useState(false);
  return <main className="min-h-screen bg-[#f7fbfc] px-5 py-8 text-[#102a43]"><div className="mx-auto max-w-[600px]"><div className="flex items-center justify-between"><Link href="/" className="flex items-center gap-2 font-semibold"><HeartPulse className="text-[#087ea4]" size={20}/> CareFirst</Link><Link href="/" className="flex items-center gap-2 text-sm text-[#627d98] transition hover:text-[#087ea4]"><ArrowLeft size={16}/> Back to website</Link></div><div className="mt-14 rounded-2xl border border-[#d9e8ed] bg-white p-7 shadow-sm sm:p-10">{done ? <div className="py-12 text-center"><h1 className="serif text-4xl">You are on your way.</h1><p className="mt-3 text-sm text-[#627d98]">Your demo profile has been created. Sign in to continue.</p><Link href="/auth/signin" className="mt-8 inline-block rounded-full bg-[#087ea4] px-6 py-3 text-sm font-semibold text-white">Go to sign in</Link></div> : <><Link href="/auth/signin" className="flex items-center gap-2 text-sm text-[#627d98]"><ArrowLeft size={16}/> Back to sign in</Link><h1 className="serif mt-10 text-4xl">Create your profile.</h1><p className="mt-2 text-sm text-[#627d98]">A simpler way to stay connected to your care.</p><form onSubmit={event => { event.preventDefault(); setDone(true); }} className="mt-8 space-y-5"><div className="grid gap-5 sm:grid-cols-2"><label className="text-xs font-semibold">Full name<input required className="mt-2 w-full rounded-lg border border-[#d9e8ed] p-3 outline-none focus:border-[#087ea4]"/></label><label className="text-xs font-semibold">Phone<input required type="tel" className="mt-2 w-full rounded-lg border border-[#d9e8ed] p-3 outline-none focus:border-[#087ea4]"/></label></div><label className="block text-xs font-semibold">Email<input required type="email" className="mt-2 w-full rounded-lg border border-[#d9e8ed] p-3 outline-none focus:border-[#087ea4]"/></label><label className="block text-xs font-semibold">Date of birth<input required type="date" className="mt-2 w-full rounded-lg border border-[#d9e8ed] p-3 outline-none focus:border-[#087ea4]"/></label><label className="block text-xs font-semibold">Create password<input required minLength="8" type="password" className="mt-2 w-full rounded-lg border border-[#d9e8ed] p-3 outline-none focus:border-[#087ea4]"/></label><label className="flex gap-2 text-xs leading-5 text-[#627d98]"><input required type="checkbox"/> I agree to the Terms of Service and Privacy Policy.</label><button className="w-full rounded-full bg-[#087ea4] py-4 text-sm font-semibold text-white">Create my profile</button></form></>}</div></div></main>;
}
